### ISSUE TITLE
Review first day of JS DOM module which comes after a lengthy break from using JS in fundamentals

### ISSUE THREAD

**Issue by vherus** [boolean-uk/software-developer#139]
Might need a lighter or warm-up first day, or a refresher of JS, before jumping into browser based JS

They'll be running code in a totally different environment, in fundamentals they use node

**Comment by dearshrewdwit** [comment]
Additional JS DOM sequence 1 LOs

- use the browser to render an html file
- use a hot reloading package like LiveServer to speed up development
- explain browsers come with JS runtime environments
- show how to link JS file in HTML pages

**Comment by dearshrewdwit** [comment]
Updated sequence 1 content 
> https://docs.google.com/presentation/d/1ghepd5Lgn0FEYCcyueDjTpA_CHR8N8NPmrmmylgQedY/edit#slide=id.gd46f8ee6d4_0_28

**Comment by vherus** [comment]
@dearshrewdwit & @dogezen to discuss observations from C8's experience

**Comment by dogezen** [comment]
Main feedback at the moment from students:
- they seem to have forgotten most JS, so covering it all in 1 morning felt a bit overwhelming at first
- most students felt they needed a bit more practice
- using JS Problems and getting students to run them in the browser was good practice, however I encouraged them to try some easy and possibly medium tasks, but would have been better to just stick to easy tasks with an option to look at medium

Suggestions for improvements
- craft a better afternoon plan for the day so that students get to cover a specific set of material and we have something to look out on montessori to evaluate progress
