### ISSUE TITLE
JS Fundamentals

### ISSUE THREAD

**Issue by dearshrewdwit** [boolean-uk/software-developer#21]
This is a proposed change to how students learn JavaScript. Significantly students will start with Nodejs, not browser JS.

Work is in this repository
> https://github.com/boolean-uk/boolean-uk-js-fundamentals

Requirements
- work from error messages (reading, understanding error messages)
- use git regularly to commit and push work
- enforce style rules, and enforce completion using precommit git hook
- write code to a specification
- Initial exposure to a test framework
- simple and clear instructions

Need
- review
- add more exercises in a similar format

**Comment by mikemherron** [comment]
We were actually discussing the JS intro at stand up this morning and agreeing the approach could potentially be changed. 

Nothing much to add at this point beyond I'm all for this, especially introducing tests earlier. I also feel doing more JS "on it's own" rather than so much "JS and the DOM" might be helpful for the students to spend more time on fundamentals. Some "JS and the DOM" could still be good as a precursor to React, but maybe not as much as we do now. One point to note could be on module ordering - if we do HTML & CSS, then Javascript Fundamentals based on Node, then back to React, is potentially confusing rather than the progression from client -> server we have now.

**Comment by glowkeeper** [comment]
there's defo way too much DOM manipulation in the current course

**Comment by dearshrewdwit** [comment]
Closing this issue. 

Issue for next iteration: https://github.com/boolean-uk/software-developer/issues/55
